pipeline {
    agent any
    tools {
       terraform 'terraform'
    }
    environment {
        WorkDir = "L12Prac/services/backend_app"
        VerTag = "${params.VerTag}"
    }
    
    parameters {
        string defaultValue: '1.0.0', description: 'Enter the version tag for this upload', name: 'VerTag', trim: true
    }

    stages {
        stage('terraform format check') {
            steps{
                dir(WorkDir) {
                    sh 'terraform fmt'
                }
            }
        }
        stage('terraform Init') {
            steps{
                withAWS(credentials: 'AWS', region: 'ap-southeast-2') {
                    dir(WorkDir) {
                        sh 'aws sts get-caller-identity'
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('terraform apply') {
            steps{
                    withAWS(credentials: 'AWS', region: 'ap-southeast-2') {
                    dir(WorkDir) {
                        sh 'terraform apply -var="app_version=$VerTag" --auto-approve'
                    }
                }
            }
        }
    }
}
